version: "3.8"
services:
  backend:
    image: temmiecvml/hyc-backend:0.0.1-dev
    restart: always
    deploy:
      replicas: 1  
    ports:
      - "8100:8100"
    env_file:
      - stack.env
    secrets:
      - openai_apikey
    networks:
      - privateoverlay

secrets:
  openai_apikey:
    external: true

networks:
  privateoverlay:
    driver: overlay