version: '3.8'
services:
  app:
    image: 'apache/airflow:slim-latest-python3.12'
    restart: unless-stopped
    ports:
      - '8080:8080'

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.id==zqayi6kamw0qhjwcn3rg9z2m4"
    
    networks: 
      - portainer_agent_network

networks:
  portainer_agent_network:
    external: true