version: '3.8'
services:
  lingua-trainer:
    image: temmiecvml/lingua_trainer:0.0.2 
    container_name: lingua-trainer
    ports:
      - "8501:8501"
    restart: always
    deploy:
      replicas: 1  
      placement:
        constraints:
          - "node.id==s0d30q8t1wmfxkx2i24m5zcad"
