version: '3.8'
services:
  lingua-trainer:
    image: temmiecvml/lingua_trainer:0.0.2-g
    container_name: lingua-trainer
    ports:
      - "8501:8501"
    restart: always
    deploy:
      replicas: 1  
