default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

services:
  - docker:dind

before_script:
  - amazon-linux-extras install docker
  - yum -y install make 
  - aws --version
  - docker --version

variables:
  DESTROY: "false"
  DEV_ENV: nlp-dev-base
  DOCKER_HOST: tcp://docker:2375


cache:
  paths:
    - .terraform

before_script:
  - amazon-linux-extras install docker
  - yum -y install make 
  - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - docker --version


stages:
  - init
  - plan
  - apply
  - destroy

init:
  stage: init
  script:
    - echo "terraform-init"
    - aws s3 ls

plan:
  stage: plan
  script:
    - echo "terraform-plan"

apply:
  stage: apply
  script:
    - echo "terraform-apply"

apply:
  stage: destroy
  script:
    - echo "terraform-destroy"
  rules:
    - if: '$DESTROY == "true"'
      when: on_success
