image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' 
    - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'

variables:
  DESTROY: "false"

stages:
  - prepare
  - finalize

init:
  stage: prepare
  script:
    - echo "terraform-init"
    - aws s3 ls

plan:
  stage: prepare
  script:
    - echo "terraform-plan"

apply:
  stage: finalize
  script:
    - echo "terraform-apply"

apply:
  stage: finalize
  script:
    - echo "terraform-destroy"
  rules:
    - if: '$DESTROY == "true"'
      when: on_success
