default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DESTROY: "false"
  DEPLOY: "true"
  DEPLOY_BRANCH: "staging"

cache:
  paths:
    - .terraform/terraform.tfstate
    - .terraform.lock.hcl


before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - cd iac
  - terraform --version
  - terraform init


stages:
  - plan
  - apply
  - destroy


plan-job:
  stage: plan
  script:
    - terraform plan -var="key_pair_name=$key_pair_name" -var="key_pair_content=$key_pair_content"
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


apply-job:
  stage: apply
  script:
    - terraform apply -var="key_pair_name=$key_pair_name" -var="key_pair_content=$key_pair_content" -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


destroy-job:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DESTROY == "true"
