stages:
  - terraform-init
  - terraform-plan
  - terraform-apply

init:
  stage: terraform-init
  script:
   - echo "terraform-init"
   - aws s3 ls

plan:
  stage: terraform-plan
  script:
   - echo "terraform-plan"

apply:
  stage: terraform-apply
  script:
   - echo "terraform-apply"

rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - if: '$CI_COMMIT_REF_NAME == "NHG-3-setup-iac-repo-with-aws-credentials-and-terraform-deployment-pipeline"'
    when: manual