default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DESTROY: "false"
  DEPLOY: "false"
  DEPLOY_BRANCH: "main"

cache:
  paths:
    - .terraform/


before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - cd iac
  - terraform --version
  - terraform init

stages:
  - deploy-manager
  - deploy-workers

manager-plan-job:
  stage: deploy-manager
  script:
    - cd iac/cluster-manager
    - terraform plan
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


manager-apply-job:
  stage: deploy-manager
  script:
    - cd iac/cluster-manager
    - terraform apply -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"

workers-plan-job:
  stage: deploy-workers
  script:
    - cd iac/cluster-workers
    - terraform plan
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


workers-apply-job:
  stage: deploy-workers
  script:
    - cd iac/cluster-workers
    - terraform apply -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


# destroy-job:
#   stage: destroy
#   script:
#     - terraform destroy -auto-approve
#   rules:
#     - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DESTROY == "true"
