default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DESTROY: "false"
  DEPLOY: "true"
  DEPLOY_BRANCH: "feature/resetup-cluster"
  TF_TOKEN_app_terraform_io: $TF_TOKEN_app_terraform_io

cache:
  paths:
    - iac/cluster-manager/.terraform/
    - iac/cluster-manager/.terraform.lock.hcl
    - iac/cluster-workers/.terraform/
    - iac/cluster-workers/.terraform.lock.hcl


before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version

stages:
  - deploy-manager
  - deploy-workers
  - destroy

manager-plan-job:
  when: manual
  stage: deploy-manager
  script:
    - terraform --version
    - cd iac/cluster-manager
    - terraform init
    - terraform plan
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


manager-apply-job:
  stage: deploy-manager
  script:
    - terraform apply -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"
  needs:
    - job: manager-plan-job
      artifacts: true

workers-plan-job:
  when: manual
  stage: deploy-workers
  script:
    - terraform --version
    - cd $CI_PROJECT_DIR/iac/cluster-workers
    - terraform init
    - terraform plan
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"


workers-apply-job:
  stage: deploy-workers
  script:
    - terraform apply -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DEPLOY == "true"
  needs:
    - job: workers-plan-job
      artifacts: true


destroy-manager-job:
  when: manual
  stage: destroy
  script:
    - export 
    - cd iac/cluster-manager
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DESTROY == "true"

destroy-workers-job:
  when: manual
  stage: destroy
  script:
    - cd $CI_PROJECT_DIR/iac/cluster-workers
    - terraform destroy -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH && $DESTROY == "true"
