default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DESTROY: "false"

cache:
  paths:
    - .terraform
    - .terraform.lock.hcl
  

before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - cd iac
  - terraform --version
  - terraform init


stages:
  - plan
  - apply
  - destroy

plan-job:
  stage: plan
  script:
    - terraform plan -var="keypair_content=$keypair_content" -var="private_key_path=$private_key_path"

apply-job:
  stage: apply
  script:
    - terraform apply -var="keypair_content=$keypair_content" -var="private_key_path=$private_key_path" -auto-approve

destroy-job:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DESTROY == "true"
      when: on_success
