default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DESTROY: "true"

cache:
  paths:
    - .terraform

before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - terraform --version
#  - terraform init

stages:
  - plan
  - apply
  - destroy

plan-job:
  stage: plan
  script:
    - echo "terraform-plan"
    - aws s3 ls

apply-job:
  stage: apply
  script:
    - echo "terraform-apply"

destroy-job:
  stage: destroy
  script:
    - echo "terraform-destroy"
  rules:
    - if: '$DESTROY == "true"'
      when: on_success
