variables:
  DESTROY: "false"

stages:
  - prepare
  - finalize

init:
  stage: prepare
  script:
   - echo "terraform-init"

plan:
  stage: prepare
  script:
   - echo "terraform-plan"

apply:
  stage: finalize
  script:
   - echo "terraform-apply"
  rules:
    - if: '$DESTROY == "false"'
        when: on_success

apply:
  stage: finalize
  script:
   - echo "terraform-destroy"
  rules:
    - if: '$DESTROY == "true"'
        when: on_success
