apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    hifeyinc.com/role: infra
spec:
  project: hifeyinc-project
  destination:
    server: https://kubernetes.default.svc
    namespace: hifeyinc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://gitlab.com/amazing_ai/gitops_temi_cluster.git
    targetRevision: main
    path: cluster/azure/namespaces/hifeyinc/charts/cert-manager
    helm:
      valueFiles: 
        - values.yaml
      values: |
        installCRDs: true
      