version: '3.8'

services:
  inspire:
    image: demo/amqp-inspire-service:0.0.2
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      - rabbitmq_rabbitmq_network

networks:
  rabbitmq_rabbitmq_network:
    external: true
