version: '3.8'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.id==92knsmf8fr4xm8kwbbmuv4tud"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/usr/david/codes-and-scripts
    
    volumes:
      - ~/.config:/config/.config

    ports:
      - 8443:8443
    restart: unless-stopped
    networks: 
      - portainer_agent_network

networks:
  portainer_agent_network:
    external: true
