version: '3.8'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.id==n9757bwj0ify7n1vd3dbkjxtp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_FILE=/run/secrets/cs_password
      - DEFAULT_WORKSPACE=/config/codes-and-scripts
    volumes:
      - /path/to/appdata/config:/config
    secrets:
      - cs_password
    ports:
      - 8443:8443
    restart: unless-stopped
    networks: 
      - portainer_agent_network

secrets:
  cs_password:
    external: true

networks:
  portainer_agent_network:
    external: true
