version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' 
      - '443:443' 
      - '81:81' 
    deploy:
      replicas: 1  
      placement:
        constraints:
          - "node.id==t46vi095zn7vrw5huq5abvm64"
