version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    deploy:
      replicas: 1  
    ports:
      - 27000:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

volumes:
  mongodb_data:

