version: "3.8"
services:
  streamlit:
    image: temmiecvml/hyc-streamlit-apps:0.0.1
    restart: always
    deploy:
      replicas: 1  
      placement:
        constraints:
          - "node.id==s0d30q8t1wmfxkx2i24m5zcad"
    ports:
      - "8501:8501"
