version: "3.8"
services:
  streamlit:
    image: temmiecvml/hyc-streamlit-apps:0.0.1-dev
    env_file:
      - stack.env
    restart: always
    deploy:
      replicas: 1  
    ports:
      - "8501:8501"
    networks:
      - privateoverlay

networks:
  privateoverlay:
    external: true
